# -*- coding: utf-8 -*-
"""ayt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5DI0yv_zyAKraAKTxIhFQQbQnTRPUyr
"""

import pandas as pd

# Dosyayı tekrar oku
df = pd.read_csv('lisans_temiz.csv')

# Mevcut sütun isimlerini yazdır (Hata buradan kaynaklanıyor)
print("Senin dosmandaki sütun isimleri şunlar:")
print(df.columns.tolist())

# 1. Sütunları standart isimlere çevirelim (Hata almamak için)
# Eğer senin sütunların farklıysa burayı ona göre eşleştirelim
# Önceki temizlikte 'min_score' yaptıysak onu 'score' yapalım:
if 'min_score' in df.columns:
    df = df.rename(columns={'min_score': 'score'})
elif 'En Küçük Puan' in df.columns:
    df = df.rename(columns={'En Küçük Puan': 'score'})

# 2. Şimdi temizliğe devam edebiliriz (Artık 'score' sütunu var!)
print(f"Toplam satır (başlangıç): {len(df)}")

# Puanı boş olanları atalım
df_clean = df.dropna(subset=['score'])

# Puanları sayıya çevirelim (Hata payını silmek için)
df_clean['score'] = pd.to_numeric(df_clean['score'], errors='coerce')

# Puanı 0'dan büyük olanları tutalım
df_clean = df_clean[df_clean['score'] > 0]

print(f"Temizlik sonrası kalan satır: {len(df_clean)}")
print("\nVerinin son hali (İlk 5 Satır):")
display(df_clean.head())

# Sütun isimlerini standartlaştıralım (Hata almamak için)
df_clean = df_clean.rename(columns={
    'score_type': 'type',
    'min_score': 'score'
})

# Şimdi tekrar kontrol edelim
print("Puan Türü Dağılımı:")
print(df_clean['type'].value_counts())

import numpy as np

# 2024 Yılı Yaklaşık Puan-Sıralama Verileri (Modelin Eğitim Seti)
yks_verileri = {
    'SAY': {
        550: 1, 500: 5000, 450: 30000, 400: 85000, 350: 180000, 300: 320000, 250: 550000, 200: 900000
    },
    'EA': {
        550: 1, 500: 1500, 450: 12000, 400: 55000, 350: 160000, 300: 400000, 250: 850000, 200: 1500000
    },
    'SOZ': {
        550: 1, 500: 500, 450: 5000, 400: 25000, 350: 90000, 300: 250000, 250: 600000, 200: 1200000
    },
    'TYT': {
        550: 1, 500: 10000, 450: 60000, 400: 180000, 350: 450000, 300: 950000, 250: 1800000, 200: 2800000
    }
}

def siralama_tahmin_et(puan, tur):
    if tur not in yks_verileri:
        return "Geçersiz Puan Türü"

    # İlgili puan türünün verilerini al
    tablo = yks_verileri[tur]
    puanlar = sorted(list(tablo.keys()))
    siralamalar = [tablo[p] for p in puanlar]

    # Numpy Interp kullanarak aradaki değeri tahmin edelim (Lineer Interpolation)
    # Puanlar arttıkça sıralama küçüldüğü için veriyi ters çevirerek işliyoruz
    tahmin = np.interp(puan, puanlar, siralamalar)

    return int(tahmin)

# TEST: Sayısal 435 puan alan birinin tahmini sıralaması
test_puan = 435
test_tur = 'SAY'
sonuc = siralama_tahmin_et(test_puan, test_tur)
print(f"{test_tur} {test_puan} Puan İçin Tahmini Sıralama: {sonuc}")

# 1. Önce sütunların dosyadaki orijinal isimlerini öğrenci/yazılımcı dostu yapalım
# Not: Senin dosyadaki orijinal isimlere göre bu sözlüğü hazırladım
rename_dict = {
    'university_name': 'univ',
    'program_name': 'dept',
    'score_type': 'type',
    'min_score': 'score'
}

# Sütunları yeniden adlandır
df_clean = df_clean.rename(columns=rename_dict)

# 2. Eğer hala isimler farklıysa (bazı versiyonlarda Türkçe olabiliyor), kontrol edelim:
if 'univ' not in df_clean.columns:
    # Orijinal Türkçe isimler varsa onları da çevirelim
    tr_rename = {
        'Üniversite Adı': 'univ',
        'Program Adı': 'dept',
        'Puan Türü': 'type',
        'En Küçük Puan': 'score'
    }
    df_clean = df_clean.rename(columns=tr_rename)

# Şimdi sıralama tahminini tekrar çalıştıralım (Hata almamak için sütunları kontrol ederek)
print("Güncel Sütunlar:", df_clean.columns.tolist())

# Sıralama sütununu ekleyelim
df_clean['est_ranking'] = df_clean.apply(lambda row: siralama_tahmin_et(row['score'], row['type']), axis=1)

# Şimdi ekrana yazdıralım (Hata almayacaksın)
display(df_clean[['univ', 'dept', 'type', 'score', 'est_ranking']].head(10))

def yks_sonuc_hesapla(tyt_netleri, ayt_netleri, obp):
    # Katsayılar (Yaklaşık 2024 değerleri)
    katsayi = {
        'tyt_tur': 3.3, 'tyt_sos': 3.4, 'tyt_mat': 3.3, 'tyt_fen': 3.4,
        'ayt_mat': 3.0, 'ayt_fiz': 2.85, 'ayt_kim': 3.07, 'ayt_biyo': 3.07,
        'ayt_edb': 3.0, 'ayt_tar1': 2.8, 'ayt_cog1': 3.3
    }

    # 1. TYT Puanı (Taban 100 + Netler)
    tyt_puani = 100
    for ders, net in tyt_netleri.items():
        tyt_puani += net * katsayi.get(ders, 0)

    # 2. AYT Sayısal Puanı (Örnek olarak)
    ayt_say_puani = tyt_puani * 0.4 + 100 # Basitleştirilmiş formül
    for ders, net in ayt_netleri.items():
        ayt_say_puani += net * katsayi.get(ders, 0)

    # 3. OBP Ekleme
    yerlestirme_say = ayt_say_puani + (obp * 0.6)

    # 4. Sıralama Tahmini
    tahmini_siralama = siralama_tahmin_et(yerlestirme_say, 'SAY')

    return round(yerlestirme_say, 2), tahmini_siralama

# ÖRNEK KULLANIM
tyt = {'tyt_tur': 30, 'tyt_mat': 35, 'tyt_sos': 15, 'tyt_fen': 15}
ayt = {'ayt_mat': 35, 'ayt_fiz': 10, 'ayt_kim': 10, 'ayt_biyo': 10}
puan, sira = yks_sonuc_hesapla(tyt, ayt, 90)

print(f"Puanın: {puan} | Tahmini Sıralaman: {sira}")

import plotly.express as px
import plotly.graph_objects as go

def basari_grafiklerini_ciz(kullanici_puani, puan_turu):
    # 1. Veriyi Filtrele (Puan türüne uygun ve puanın yettiği bölümler)
    firsatlar = df_clean[(df_clean['type'] == puan_turu) & (df_clean['score'] <= kullanici_puani)].copy()
    firsatlar = firsatlar.sort_values(by='score', ascending=False).head(10)

    # 2. Bar Grafik: Girebileceğin En İyi 10 Bölüm
    fig1 = px.bar(
        firsatlar,
        x='score',
        y='dept',
        color='score',
        hover_data=['univ'],
        title=f"Puanınla Girebileceğin En İyi 10 Bölüm ({puan_turu})",
        labels={'score': 'Taban Puan', 'dept': 'Bölüm Adı'},
        color_continuous_scale='Viridis'
    )
    fig1.update_layout(yaxis={'categoryorder':'total ascending'}, template="plotly_dark")
    fig1.show()

    # 3. Yoğunluk Grafiği: Tüm Türkiye İçindeki Konumun
    genel_puanlar = df_clean[df_clean['type'] == puan_turu]['score']

    fig2 = go.Figure()
    # Tüm puanların dağılımı
    fig2.add_trace(go.Histogram(
        x=genel_puanlar,
        name='Bölüm Dağılımı',
        marker_color='#330C73',
        opacity=0.6
    ))
    # Kullanıcının puanı (Dikey Çizgi)
    fig2.add_vline(
        x=kullanici_puani,
        line_width=3,
        line_dash="dash",
        line_color="red",
        annotation_text="SENİN PUANIN",
        annotation_position="top right"
    )

    fig2.update_layout(
        title=f"Puanının Türkiye Dağılımındaki Yeri ({puan_turu})",
        xaxis_title="Puan",
        yaxis_title="Bölüm Sayısı",
        template="plotly_dark"
    )

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
import numpy as np

# 1. Puan türlerini (SAY, EA, vb.) sayısal verilere çevirelim
le = LabelEncoder()
df_clean['type_encoded'] = le.fit_transform(df_clean['type'])

# 2. X (Giriş: Puan ve Tür) ve y (Çıkış: Sıralama) değerlerini belirleyelim
X = df_clean[['score', 'type_encoded']]
y = df_clean['est_ranking']

# 3. Veriyi Eğitim ve Test olarak ikiye bölelim (%80 Eğitim, %20 Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Model eğitim için hazır!")

# 1. 'est_ranking' sütunundaki verileri sayıya çevirmeyi dene, çevrilemeyenleri (metinleri) NaN yap
df_clean['est_ranking'] = pd.to_numeric(df_clean['est_ranking'], errors='coerce')

# 2. NaN olan (yani 'Geçersiz Puan Türü' yazan) satırları tamamen sil
df_final = df_clean.dropna(subset=['est_ranking']).copy()

# 3. Şimdi X ve y'yi tekrar tanımlayalım (Yeni temiz veri setimizle)
X = df_final[['score', 'type_encoded']]
y = df_final['est_ranking']

# 4. Tekrar bölme işlemi yapalım
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Hatalı satırlar temizlendi. Yeni veri sayısı: {len(df_final)}")

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

score = model.score(X_test, y_test)
print(f"Model Başarı Oranı: %{score*100:.2f}")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# 1. Tahminleri alalım
y_pred = model.predict(X_test)

# 2. Sıralama dilimlerini (bin) belirleyelim
# Örn: 0-20k, 20k-50k, 50k-150k, 150k-500k, 500k+
bins = [0, 20000, 50000, 150000, 500000, 2000000]
labels = ['0-20k', '20k-50k', '50k-150k', '150k-500k', '500k+']

# 3. Gerçek ve tahmin edilen değerleri bu dilimlere yerleştirelim
y_test_binned = pd.cut(y_test, bins=bins, labels=labels)
y_pred_binned = pd.cut(y_pred, bins=bins, labels=labels)

# 4. Karışıklık Matrisini hesaplayalım
cm = confusion_matrix(y_test_binned, y_pred_binned, labels=labels)

# 5. Görselleştirelim
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
plt.title('Sıralama Dilimi Tahmin Başarısı (Confusion Matrix)')
plt.xlabel('Modelin Tahmini')
plt.ylabel('Gerçek Sıralama Dilimi')
plt.show()

