# -*- coding: utf-8 -*-
"""tyt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p40zX0jIRCLE2Qft9T_iq-J2KyjPC7Y-
"""

import pandas as pd
import numpy as np

# 1. TYT Verisini Yükle
df_tyt = pd.read_csv('on_lisans_temiz.csv')

# 2. Sütun İsimlerini Düzelt
df_tyt = df_tyt.rename(columns={
    'university_name': 'univ',
    'program_name': 'dept',
    'score_type': 'type',
    'min_score': 'score'
})

# 3. TYT Sıralama Verisi (Yaklaşık 2024)
tyt_yiginsal = {
    550: 1, 500: 10000, 450: 60000, 400: 180000,
    350: 450000, 300: 950000, 250: 1800000, 200: 2800000
}

def tyt_sira_bul(puan):
    puanlar = sorted(list(tyt_yiginsal.keys()))
    siralar = [tyt_yiginsal[p] for p in puanlar]
    return int(np.interp(puan, puanlar, siralar))

# 4. Sıralamaları Hesapla
df_tyt = df_tyt.dropna(subset=['score'])
df_tyt = df_tyt[df_tyt['score'] > 0]
df_tyt['est_ranking'] = df_tyt['score'].apply(tyt_sira_bul)

print(f"TYT Veri Seti Hazır: {len(df_tyt)} Satır")

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Özellikleri Belirle
X_t = df_tyt[['score']] # TYT'de tek puan türü olduğu için sadece score yeterli
y_t = df_tyt['est_ranking']

X_train_t, X_test_t, y_train_t, y_test_t = train_test_split(X_t, y_t, test_size=0.2, random_state=42)

# Modeli Eğit
model_tyt = RandomForestRegressor(n_estimators=100, random_state=42)
model_tyt.fit(X_train_t, y_train_t)

# Tahminleri Al ve Matrisi Çiz
y_pred_t = model_tyt.predict(X_test_t)

# TYT Dilimleri: 0-100k, 100k-300k, 300k-600k, 600k-1M, 1M+
bins_t = [0, 100000, 300000, 600000, 1000000, 4000000]
labels_t = ['0-100k', '100k-300k', '300k-600k', '600k-1M', '1M+']

y_test_b_t = pd.cut(y_test_t, bins=bins_t, labels=labels_t)
y_pred_b_t = pd.cut(y_pred_t, bins=bins_t, labels=labels_t)

cm_t = confusion_matrix(y_test_b_t, y_pred_b_t, labels=labels_t)

plt.figure(figsize=(10, 8))
sns.heatmap(cm_t, annot=True, fmt='d', cmap='Greens', xticklabels=labels_t, yticklabels=labels_t)
plt.title('TYT Sıralama Tahmin Başarısı')
plt.show()

